Development-Urban-Codesign/ucode-v2

.github/workflows/ci_cd.yml, README.md, backend/.gitignore, backend/.vscode/extensions.json, backend/.vscode/settings.json, backend/Makefile, backend/README.md, backend/demo_service.py, backend/main.py, backend/requirements-dev.txt, backend/requirements.txt, backend/test_demo_service.py, backend/test_dummy.py, backend/test_main.py
Added unit tests to the backend with *pytest*.
Added the test step into the continuous integration pipeline.
=> feat(backend):unit tests

backend/main.py
added to the overpass request for buildings, to also get building:parts. More details and missing parts of some buildings are shown.
=> added osm buildingparts for the building visualisation

backend/db.py, backend/main.py, frontend/src/components/AOI.vue, frontend/src/store/modules/aoi.js
I added a small user feedback for clicking the get button for greenery and buildings
=> added UI feedback for getting Data and when it is stored in db

backend/db.py, backend/main.py, frontend/src/components/CommentPopupContent.vue, frontend/src/components/Contribution.vue, frontend/src/components/LinePopupContent.vue, frontend/src/components/Map.vue, frontend/src/service/backend.service.js, frontend/src/store/modules/contribution.js, frontend/src/store/modules/map.js
The tool contains the following features:
1.  Interactive multiple line drawing
2. writing a comment
3. modifying line width and color in real-time (before submit)
4. possibility to cancel or submit the contribution (drawn line)
5. after submit, the line will be added to the scene and will be inserted into the database table (drawnline) with the assigned attributes (description, width, color).
6. The database table has the following specifications:
_create table if not exists drawnline (id SERIAL PRIMARY KEY, comment VARCHAR (300), color CHAR(7), width FLOAT(2),geom geometry(LINESTRING, 4326));_
=> UCD-44-import-tram-routes

backend/db.py, backend/main.py, frontend/src/components/Comment.vue, frontend/src/components/Map.vue, frontend/src/service/backend.service.js, frontend/src/store/modules/comment.js, frontend/src/store/store.js
Visualize and query contribution (comment).
- The comment table has been created as follows:
_create table comment (id SERIAL NOT NULL PRIMARY KEY, comment TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), likes integer DEFAULT 0, dislikes integer DEFAULT 0, geom geometry(Point, 4326));_
- The comments are visualized as the map component is mounted
- The comments are visualized with 3D icons
- Comments can be queried by clicking on them
- The corresponding comment information is shown on the right panel including date, number of likes, dislikes, and main comment text
- the panel is togglable
=> Ucd 33 show contributions

backend/db.py, backend/main.py, frontend/src/components/Comment.vue, frontend/src/store/modules/comment.js
**Add like and dislikes on comments**
- user can vote on comments in form of likes and dislike
- the vote can be changed (undo like and dislike)
- the votes are hidden if the user has not already voted on comments (in order to avoid biased opinion)
- the votes on comments are saved on the comment table
- No user has been defined so far.
=> Ucd 34 likes

frontend/src/components/Comment.vue, frontend/src/components/Contribution.vue, frontend/src/components/Map.vue, frontend/src/service/backend.service.js, frontend/src/store/modules/pulse.js, frontend/src/store/store.js, frontend/src/utils/pulseLayer.js
In this PR, the module has been created and tested for a click event on the _comment_  layer. The behavior is as follows:
- a click event is defined on the main dataset (comment) to identify the location of the clicked comment
- the location is sent to the vuex pulse store
- the pulse layer is added to the map
- the pulse layer gets two parameter: 1- location of the pulse 2- animation instance
- After adding the pulse layer, the animation with varying radius and opacity is created
- after clicking on close button, the animation is sopped and the pulse layer is removed
- The animation should be stopped by calling   _cancelAnimationFrame(store.state.pulse.pulseAnimationActivation)_. otherwise it would be CPU consuming
=> Pulse layer - A reusable and generic module for creating pulse animation around a clicked point feature.

backend/db.py, backend/main.py, frontend/src/components/AOI.vue, frontend/src/service/backend.service.js
- retrieving trees from osm using overpass API
- storing them in the database table named _tree_
- The tree table has been created as following: 
_create table tree (id SERIAL PRIMARY KEY, geom geometry(Point, 4326));_
-  An API is defined to fetch the trees from the database on user request
- The fetched data are visualized using DeckGL's _ScenegraphLayer_
=> Ucd 40 show trees

.github/workflows/ci_cd.yml, backend/db.py, backend/db_migrations.py, backend/db_migrations/0001.create-initial-tables.sql, backend/main.py, backend/requirements.txt
Add the ability to programatically execute database migrations on every serer start using this tool: https://ollycope.com/software/yoyo/latest/
=> feat: added database migrations on every server start

README.md
=> doc: added useful commands for debugging and state monitoring on the deployed environment

Caddyfile
Enable compression of common result types in order to transfer smaller files to the clients. 
Will be applied to the following file types:
```
[match](https://caddyserver.com/docs/caddyfile/directives/encode#match) {
[header](https://caddyserver.com/docs/caddyfile/directives/encode#header) Content-Type text/*
[header](https://caddyserver.com/docs/caddyfile/directives/encode#header) Content-Type application/json*
[header](https://caddyserver.com/docs/caddyfile/directives/encode#header) Content-Type application/javascript*
[header](https://caddyserver.com/docs/caddyfile/directives/encode#header) Content-Type application/xhtml+xml*
[header](https://caddyserver.com/docs/caddyfile/directives/encode#header) Content-Type application/atom+xml* …
```
=> feat: compress the contents of the server responses to increase loading times

frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/components/AOI.vue, frontend/src/components/Quests.vue, frontend/src/localization.json, frontend/src/main.js, frontend/src/plugins/i18n.js
Add i18n functionality with the http://vue-i18n.intlify.dev/ library.
- feat: add i18n
- feat: externalize i18n file
- feat: change language from url hash
- feat: start translating the quest component
- feat: showcased localization functionality inside a label
=> Add i18n functionality

backend/db.py, backend/db_migrations/0003.project-table-initialization.sql, backend/main.py, frontend/src/components/AOI.vue, frontend/src/components/DevUI.vue, frontend/src/store/modules/aoi.js
this PR creates an API that gets the project specification from the database and set the information in the frontend
=> Ucd 195 update aoi frontend

frontend/src/components/Map.vue, frontend/src/components/PlanningIdeas.vue
Optimize the navigation to the planning ideas data by watching ui store to check if the AOI is created and the project is loaded
=> Ucd 257 bird view camera at start

frontend/src/components/Map.vue
subscribe to addLayer and addSource inside map.on("load") function in order to avoid "style is not done loading" error
=> subscribe to addlayer,addsource inside map.on(load) function

frontend/src/components/Map.vue
conditional rendering if the map is loaded against components
=> Style is not done loading

frontend/src/components/AOI.vue, frontend/src/components/Contribution.vue, frontend/src/components/Map.vue
Use the `devMode` value from the ui store exclusively.
=> feat: moved the dev mode checks to the ui store completely

frontend/src/components/PlanningIdeas.vue
In this PR the color of the selected button is changed, if selected, in the route planning buttons.
=> change selected active btn in route filter btns

frontend/src/components/PlanningIdeas.vue
This PR solves the visualization of the overlapping lines by defining offset in the rendering process.
Another alternative for solving this issue is to manipulate the line geometry in the PostGIS database.
=> offset overlapping lines

backend/Dockerfile, backend/README.md
Updated the python version in the backend container to 3.11 in order to benefit from the latest performance improvements promising up to 20x performance boost in some cases @see https://docs.python.org/3.11/whatsnew/3.11.html
=> feat: updated python to 3.11 in the backend docker container

backend/main.py
added fountains to water layer - look nice in parks and the city
double overpass quarry needed - don't know why one query didn't work..
=> added fountains as extra overpass query, because combine didnt work

backend/main.py
fixed: some buildings with multiparts not showing correctly
=> Ucd 406 fix building with hole data

frontend/src/components/Contribution.vue, frontend/src/components/DevUI.vue, frontend/src/components/Map.vue
Moved dev-buttons from Map.vue to DevUI.vue and arraged them in a meaningful way
=> Ucd 411 clean up dev UI components

backend/main.py
=> fixed faulty overpass querries
